"""OpenAPI schema prepared for Dify custom tools.

Dify custom tools are stricter than FastAPI's built-in docs page. FastAPI
currently generates OpenAPI 3.1.0, while many Dify versions expect OpenAPI
3.0.x. This module keeps a small, explicit OpenAPI 3.0.3 document for Dify.

The schema only exposes the four useful health endpoints. It intentionally
does not expose `/` or `/docs`, because those endpoints are for humans, not
for an agent tool.
"""

from typing import Any


def get_dify_openapi_schema() -> dict[str, Any]:
    """Return a Dify-compatible OpenAPI 3.0.3 schema.

    Data flow:
    1. Dify calls `http://192.168.1.103:8000/dify-openapi.json`.
    2. FastAPI routes the request to `app.main.dify_openapi()`.
    3. `dify_openapi()` calls this function.
    4. This function returns a plain Python dict.
    5. FastAPI serializes the dict to JSON.

    Why this is separate from `/openapi.json`:
    - `/openapi.json` is generated by FastAPI and currently uses 3.1.0.
    - Dify custom tools are usually happier with OpenAPI 3.0.3.
    - A small manual schema is easier to control while learning.
    """

    return {
        "openapi": "3.0.3",
        "info": {
            "title": "inner-ai-tools",
            "description": (
                "Internal read-only health check tools for Docker, Ollama, "
                "Dify, and Milvus."
            ),
            "version": "0.1.0",
        },
        "servers": [
            {
                "url": "http://192.168.1.103:8000",
                "description": "FastAPI service running on the Windows host.",
            }
        ],
        "paths": {
            "/health/docker": {
                "get": {
                    "operationId": "checkDockerHealth",
                    "summary": "Check Docker health",
                    "description": (
                        "Read-only Docker health check. It can check local "
                        "Docker CLI or remote Docker through SSH, depending "
                        "on the FastAPI server environment variables. "
                        "This operation has no input parameters; call it with an empty JSON object {}."
                    ),
                    "parameters": [],
                    "responses": {
                        "200": {
                            "description": "Docker health check result.",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "$ref": "#/components/schemas/HealthCheckResult"
                                    }
                                }
                            },
                        }
                    },
                }
            },
            "/health/ollama": {
                "get": {
                    "operationId": "checkOllamaHealth",
                    "summary": "Check Ollama health",
                    "description": (
                        "Checks whether the Ollama service is reachable and "
                        "returns model count and model names. "
                        "This operation has no input parameters; call it with an empty JSON object {}."
                    ),
                    "parameters": [],
                    "responses": {
                        "200": {
                            "description": "Ollama health check result.",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "$ref": "#/components/schemas/HealthCheckResult"
                                    }
                                }
                            },
                        }
                    },
                }
            },
            "/health/dify": {
                "get": {
                    "operationId": "checkDifyHealth",
                    "summary": "Check Dify health",
                    "description": (
                        "Checks whether the Dify web service is reachable. "
                        "This operation has no input parameters; call it with an empty JSON object {}."
                    ),
                    "parameters": [],
                    "responses": {
                        "200": {
                            "description": "Dify health check result.",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "$ref": "#/components/schemas/HealthCheckResult"
                                    }
                                }
                            },
                        }
                    },
                }
            },
            "/health/milvus": {
                "get": {
                    "operationId": "checkMilvusHealth",
                    "summary": "Check Milvus health",
                    "description": (
                        "Checks whether the Milvus TCP port is reachable. "
                        "It does not read or write collections. "
                        "This operation has no input parameters; call it with an empty JSON object {}."
                    ),
                    "parameters": [],
                    "responses": {
                        "200": {
                            "description": "Milvus health check result.",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "$ref": "#/components/schemas/HealthCheckResult"
                                    }
                                }
                            },
                        }
                    },
                }
            },
        },
        "components": {
            "schemas": {
                "HealthCheckResult": {
                    "type": "object",
                    "required": [
                        "service",
                        "ok",
                        "status",
                        "checked_at",
                        "response_time_ms",
                        "details",
                    ],
                    "properties": {
                        "service": {
                            "type": "string",
                            "description": "Service name, such as docker or ollama.",
                            "example": "ollama",
                        },
                        "ok": {
                            "type": "boolean",
                            "description": "Whether the health check passed.",
                            "example": True,
                        },
                        "status": {
                            "type": "string",
                            "description": "Human-readable health status.",
                            "enum": ["healthy", "unhealthy"],
                            "example": "healthy",
                        },
                        "checked_at": {
                            "type": "string",
                            "format": "date-time",
                            "description": "Check timestamp.",
                            "example": "2026-06-10T08:09:05Z",
                        },
                        "response_time_ms": {
                            "type": "number",
                            "format": "double",
                            "description": "Check duration in milliseconds.",
                            "example": 1521.19,
                        },
                        "details": {
                            "type": "object",
                            "description": "Service-specific diagnostic details.",
                            "additionalProperties": True,
                            "example": {
                                "url": "http://192.168.1.106:11434/api/tags",
                                "status_code": 200,
                                "model_count": 1,
                            },
                        },
                    },
                }
            }
        },
    }
